# Dockerfile.frontend
FROM node:20-alpine

WORKDIR /app

COPY front-end/package*.json ./
RUN npm install

COPY front-end/ .

# Ajout d'une étape de développement pour vérifier les erreurs
RUN npm run build || (echo "Build failed. Check your import paths." && exit 1)

EXPOSE 3000
CMD ["npm", "run", "dev"]